version: "3.3"

services:
  leitor-vendedor:
    image: "leituravendedor:${CODE_SC_HG}"
    ports:
      - 8042:8042
    environment:
      - spring_datasource_url=jdbc:postgresql://172.18.0.1/gnus
      - s3_host=http://172.18.0.1:9444/s3
      - kafka_bootstrap-servers=172.18.0.1:9092
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

